version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
      - image: postgres
        environment:
          POSTGRES_USER: notetaker_test
          POSTGRES_PASSWORD: "testpassword"
          POSTGRES_DB: test_notetaker

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: app/tests
          