# Generated by Django 3.0.8 on 2020-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200726_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='total_attendance',
            field=models.PositiveIntegerField(),
        ),
    ]
